version: 2.1
executors:
  default:
    docker:
      - image: filecoin/rust:latest
    working_directory: /mnt/crate
  doxygen:
    docker:
      - image: hrektts/doxygen
            
jobs:
  build_doxygen:
    executor: doxygen
    steps:
      - checkout
      - run: bash scripts/run-doxygen.sh
      - run: mkdir -p workspace/c-docs
      - run: cp -av deltachat-ffi/{html,xml} workspace/c-docs/
      - persist_to_workspace:
          root: workspace
          paths:
            - c-docs

  remote_python_packaging:
    machine: true
    steps:
      - checkout
      # the following commands on success produces
      # workspace/{wheelhouse,py-docs} as artefact directories
      - run:
          # building aarch64 packages under qemu is very slow
          no_output_timeout: 60m
          command: bash scripts/remote_python_packaging.sh
      - persist_to_workspace:
          root: workspace
          paths:
            # - c-docs
            - py-docs
            - wheelhouse

  upload_docs_wheels:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: ls -laR workspace
      - run: scripts/ci_upload.sh workspace/py-docs workspace/wheelhouse workspace/c-docs

workflows:
  version: 2.1

  test:
    jobs:
      - remote_python_packaging:
          filters:
            tags:
              only: /.+/

      - build_doxygen:
          filters:
            tags:
              only: /.+/

      - upload_docs_wheels:
          requires:
             - remote_python_packaging
             - build_doxygen
          filters:
            tags:
              only: /.+/
