[package]
name = "deltachat_ffi"
version = "1.69.0"
description = "Deltachat FFI"
authors = ["Delta Chat Developers (ML) <delta@codespeak.net>"]
edition = "2018"
readme = "README.md"
license = "MPL-2.0"

keywords = ["deltachat", "chat", "openpgp", "email", "encryption"]
categories = ["cryptography", "std", "email"]

[lib]
name = "deltachat"
crate-type = ["cdylib", "staticlib"]

[dependencies]
deltachat = { path = "../", default-features = false }
libc = "0.2"
human-panic = "1"
num-traits = "0.2"
serde_json = "1.0"
async-std = "1"
anyhow = "1"
thiserror = "1"
rand = "0.7"

[features]
default = ["vendored"]
vendored = ["deltachat/vendored"]
nightly = ["deltachat/nightly"]

