[package]
name = "deltachat_derive"
version = "2.0.0"
authors = ["Delta Chat Developers (ML) <delta@codespeak.net>"]
edition = "2018"
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.74"
quote = "1.0.2"
