name: JSON-RPC API Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Build
        run: cargo build --verbose --features webserver -p deltachat-jsonrpc
      - name: Run tests
        run: cargo test --verbose --features webserver -p deltachat-jsonrpc

  ts_bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: npm i
        run: |
          cd deltachat-jsonrpc/typescript
          npm i
      - name: npm run generate-bindings
        run: |
          cd deltachat-jsonrpc/typescript
          npm run generate-bindings
      - name: npm run check ts
        run: |
          cd deltachat-jsonrpc/typescript
          npx tsc --noEmit
      - name: run integration tests
        run: |
          cd deltachat-jsonrpc/typescript
          npm run build
          cargo build --features webserver
          npm run test:integration
      - name: run prettier
        run: |
          cd deltachat-jsonrpc/typescript
          npm run prettier:check
