# Manually triggered GitHub Actions workflow
# to build a Windows repl.exe which users can
# download to debug complex bugs.

name: Build Windows REPL .exe

on:
  workflow_dispatch:

permissions: {}

jobs:
  build_repl:
    name: Build REPL example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: nix build .#deltachat-repl-win64
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: repl.exe
          path: "result/bin/deltachat-repl.exe"
